
import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 
  | 'id' // Indonesian
  | 'en' // English
  | 'zh' // Chinese
  | 'it' // Italian
  | 'fr' // French
  | 'ja' // Japanese
  | 'ko' // Korean
  | 'ar' // Arabic
  | 'es'; // Spanish

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: { code: Language; label: string }[];
}

const availableLanguages: { code: Language; label: string }[] = [
  { code: 'id', label: 'Indonesia' },
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文 (Chinese)' },
  { code: 'it', label: 'Italiano' },
  { code: 'fr', label: 'Français' },
  { code: 'ja', label: '日本語 (Japanese)' },
  { code: 'ko', label: '한국어 (Korean)' },
  { code: 'es', label: 'Español (Spanish)' },
  { code: 'ar', label: 'العربية (Arabic)' },
];

const translations: Record<Language, Record<string, string>> = {
  id: {
    loginTitle: "LOGIN EKSKLUSIF 2026",
    loginSubtitle: "Masuk untuk merayakan tahun baru bersama GUCCI & E-Partner.",
    fullName: "Nama Lengkap",
    phoneNumber: "Nomor HP",
    password: "Kode Akses",
    startJourney: "MULAI PERAYAAN",
    menu: "VISI & MISI",
    validUntil: "Berlaku Hingga",
    claimReward: "Lihat E-Ticket",
    officialWinner: "Pemenang Eksklusif",
    screenshotInstruction: "UNDUH E-TICKET TAHUN BARU",
    welcomeTitle: "GUCCI X E-PARTNER GALA 2026",
    welcomeText: "Sambut perayaan akhir tahun 2025 menuju tahun baru 2026. Gucci bersama Bisnis E-Partner mempersembahkan kado spesial tahun baru bagi Anda yang beruntung. Temukan hadiah eksklusif mulai dari Rp 250.000 hingga puluhan juta rupiah melalui Golden Scratch.",
    scratchHere: "Gosok Untuk Keberuntungan",
    invitation: "Undangan Gala",
    specialDiscount: "Golden Scratch 2026",
    giftVoucher: "KADO TAHUN BARU",
    redeemable: "Berlaku di Butik Gucci pilihan.",
    congratsTitle: "SELAMAT TAHUN BARU",
    voucherPrefix: "VOUCHER",
    discountPrefix: "KILAU",
    claimMessage: "Halo, saya telah memenangkan hadiah Tahun Baru dari Gucci Indonesia",
    codeLabel: "KODE KEBERUNTUNGAN",
    processRequest: "Mohon konfirmasi reservasi saya.",
    florenceSubtitle: "New Year Celebration",
    backToHome: "Kembali",
    visionTitle: "Visi & Misi 2026",
    visionText1: "Membangun Masa Depan Kemewahan",
    visionText2: "Gucci berkomitmen untuk terus berinovasi dalam setiap langkah kreatif menuju tahun 2026. Kami menghadirkan perpaduan antara warisan budaya yang kaya dengan teknologi masa depan, memastikan setiap pelanggan merasakan standar pelayanan premium yang tak tertandingi.",
    expiryDate: "15 Januari 2026",
  },
  en: {
    loginTitle: "EXCLUSIVE 2026 LOGIN",
    loginSubtitle: "Sign in to celebrate the new year with GUCCI & E-Partner.",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    password: "Access Code",
    startJourney: "START CELEBRATION",
    menu: "VISION & MISSION",
    validUntil: "Valid Until",
    claimReward: "View E-Ticket",
    officialWinner: "Official Winner",
    screenshotInstruction: "DOWNLOAD NEW YEAR E-TICKET",
    welcomeTitle: "GUCCI X E-PARTNER GALA 2026",
    welcomeText: "Welcome the transition from late 2025 into 2026. Gucci and Bisnis E-Partner present a special New Year gift as appreciation. Discover exclusive prizes ranging from Rp 250,000 to tens of millions of rupiah via the Golden Scratch.",
    scratchHere: "Scratch for Luck",
    invitation: "Gala Invitation",
    specialDiscount: "2026 Golden Scratch",
    giftVoucher: "NEW YEAR GIFT",
    redeemable: "Redeemable at selected Gucci Boutiques.",
    congratsTitle: "HAPPY NEW YEAR",
    voucherPrefix: "VOUCHER",
    discountPrefix: "SPARKLE",
    claimMessage: "Hello, I've won a New Year reward from Gucci Indonesia",
    codeLabel: "LUCKY CODE",
    processRequest: "Please confirm my reservation.",
    florenceSubtitle: "New Year Celebration",
    backToHome: "Back",
    visionTitle: "Vision & Mission 2026",
    visionText1: "Defining the Future of Luxury",
    visionText2: "Gucci is reinventing a wholly modern approach to fashion for the year 2026 and beyond. Under the new vision, the House has redefined luxury for the 21st century, further reinforcing its position as one of the world's most desirable fashion houses.",
    expiryDate: "15 January 2026",
  },
  zh: {
    loginTitle: "2026 专属登录",
    loginSubtitle: "登录与 GUCCI 一起庆祝新年。",
    fullName: "全名",
    phoneNumber: "电话号码",
    password: "访问码",
    startJourney: "开始庆典",
    menu: "愿景与使命",
    validUntil: "有效期至",
    claimReward: "查看电子票",
    officialWinner: "正式获胜者",
    screenshotInstruction: "下载新年电子票",
    welcomeTitle: "2026 新年庆典",
    welcomeText: "迎接 2026 年的曙光。Gucci 与 E-Partner 合作，在今晚发现您的专属惊喜。",
    scratchHere: "刮开好运",
    invitation: "晚宴邀请",
    specialDiscount: "2026 黄金刮刮乐",
    giftVoucher: "新年礼物",
    redeemable: "可在指定的 Gucci 精品店兑换。",
    congratsTitle: "新年快乐",
    voucherPrefix: "代金券",
    discountPrefix: "闪耀",
    claimMessage: "您好，我获得了来自 Gucci Indonesia 的新年奖励",
    codeLabel: "幸运代码",
    processRequest: "请确认我的预订。",
    florenceSubtitle: "新年庆典",
    backToHome: "返回",
    visionTitle: "2026 愿景与使命",
    visionText1: "定义奢华的未来",
    visionText2: "Gucci 正在为 2026 年及以后重塑一种全新的现代时尚方式。",
    expiryDate: "2026年1月15日",
  },
  it: {
    loginTitle: "ACCESSO ESCLUSIVO 2026",
    loginSubtitle: "Accedi per festeggiare il nuovo anno con GUCCI.",
    fullName: "Nome Completo",
    phoneNumber: "Numero di Telefono",
    password: "Codice di Accesso",
    startJourney: "INIZIA LA FESTA",
    menu: "VISIONE E MISSIONE",
    validUntil: "Valido Fino Al",
    claimReward: "Vedi E-Ticket",
    officialWinner: "Vincitore Ufficiale",
    screenshotInstruction: "SCARICA E-TICKET DI CAPODANNO",
    welcomeTitle: "Celebrazione Capodanno 2026",
    welcomeText: "Accogli l'alba del 2026. Gucci ed E-Partner presentano un regalo speciale per te.",
    scratchHere: "Gratta per la Fortuna",
    invitation: "Invito al Gala",
    specialDiscount: "Golden Scratch 2026",
    giftVoucher: "REGALO DI CAPODANNO",
    redeemable: "Riscattabile presso le Boutique Gucci selezionate.",
    congratsTitle: "BUON ANNO",
    voucherPrefix: "BUONO",
    discountPrefix: "LUCE",
    claimMessage: "Salve, ho vinto un premio di Capodanno da Gucci Indonesia",
    codeLabel: "CODICE FORTUNATO",
    processRequest: "Si prega di confermare la mia prenotazione.",
    florenceSubtitle: "Celebrazione di Capodanno",
    backToHome: "Indietro",
    visionTitle: "Visione e Missione 2026",
    visionText1: "Definire il Futuro del Lusso",
    visionText2: "Gucci sta reinventando un approccio del tutto moderno alla moda per l'anno 2026.",
    expiryDate: "15 Gennaio 2026",
  },
  fr: {
    loginTitle: "CONNEXION EXCLUSIVE 2026",
    loginSubtitle: "Connectez-vous pour fêter la nouvelle année avec GUCCI.",
    fullName: "Nom Complet",
    phoneNumber: "Numéro de Téléphone",
    password: "Code d'Accès",
    startJourney: "COMMENCER LA FÊTE",
    menu: "VISION ET MISSION",
    validUntil: "Valable jusqu'au",
    claimReward: "Voir l'E-Ticket",
    officialWinner: "Gagnant Officiel",
    screenshotInstruction: "TÉLÉCHARGER L'E-TICKET NOUVEL AN",
    welcomeTitle: "Célébration du Nouvel An 2026",
    welcomeText: "Bienvenue en 2026. Gucci et E-Partner vous offrent un cadeau spécial.",
    scratchHere: "Grattez pour la Chance",
    invitation: "Invitation Gala",
    specialDiscount: "Golden Scratch 2026",
    giftVoucher: "CADEAU DU NOUVEL AN",
    redeemable: "Échangeable dans les boutiques Gucci sélectionnées.",
    congratsTitle: "BONNE ANNÉE",
    voucherPrefix: "BON",
    discountPrefix: "ÉCLAT",
    claimMessage: "Bonjour, j'ai gagné une récompense du Nouvel An de Gucci Indonesia",
    codeLabel: "CODE CHANCE",
    processRequest: "Veuillez confirmer ma réservation.",
    florenceSubtitle: "Célébration Nouvel An",
    backToHome: "Retour",
    visionTitle: "Vision & Mission 2026",
    visionText1: "Définir le Futur du Luxe",
    visionText2: "Gucci réinvente une approche moderne de la mode pour l'année 2026.",
    expiryDate: "15 Janvier 2026",
  },
  ja: {
    loginTitle: "2026年 限定ログイン",
    loginSubtitle: "GUCCIと共に新年を祝うためにサインインしてください。",
    fullName: "フルネーム",
    phoneNumber: "電話番号",
    password: "アクセスコード",
    startJourney: "お祝いを始める",
    menu: "ビジョン＆ミッション",
    validUntil: "有効期限",
    claimReward: "電子チケットを表示",
    officialWinner: "公式当選者",
    screenshotInstruction: "新年電子チケットをダウンロード",
    welcomeTitle: "2026年 新年のお祝い",
    welcomeText: "2026年の夜明けへ。グッチとEパートナーより新年の贈り物です。",
    scratchHere: "スクラッチして幸運を",
    invitation: "ガラへの招待",
    specialDiscount: "2026 ゴールデンスクラッチ",
    giftVoucher: "新年の贈り物",
    redeemable: "一部のGucciブティックでご利用いただけます。",
    congratsTitle: "明けましておめでとうございます",
    voucherPrefix: "バウチャー",
    discountPrefix: "輝き",
    claimMessage: "こんにちは、Gucci Indonesiaから新年的特典を獲得しました",
    codeLabel: "ラッキーコード",
    processRequest: "予約を確認してください。",
    florenceSubtitle: "新年のお祝い",
    backToHome: "戻る",
    visionTitle: "2026年 ビジョン＆ミッション",
    visionText1: "ラグジュアリーの未来を定義する",
    visionText2: "グッチは、2026年以降に向けて、完全に現代的なファッションへのアプローチを再構築しています。",
    expiryDate: "2026年1月15日",
  },
  ko: {
    loginTitle: "2026년 독점 로그인",
    loginSubtitle: "GUCCI와 함께 새해를 축하하기 위해 로그인하세요.",
    fullName: "성함",
    phoneNumber: "전화번호",
    password: "액세스 코드",
    startJourney: "축제 시작",
    menu: "비전 및 미션",
    validUntil: "유효 기간",
    claimReward: "전자 티켓 보기",
    officialWinner: "공식 당첨자",
    screenshotInstruction: "새해 전자 티켓 다운로드",
    welcomeTitle: "2026년 새해 축제",
    welcomeText: "2026년의 새벽을 맞이하세요. 구찌와 E-Partner가 드리는 특별한 선물입니다.",
    scratchHere: "행운을 위해 긁으세요",
    invitation: "갈라 초대장",
    specialDiscount: "2026 골든 스크래치",
    giftVoucher: "새해 선물",
    redeemable: "선택된 Gucci 부티크에서 사용 가능합니다.",
    congratsTitle: "새해 복 많이 받으세요",
    voucherPrefix: "바우처",
    discountPrefix: "광채",
    claimMessage: "안녕하세요, Gucci Indonesia로부터 새해 보상을 받았습니다",
    codeLabel: "행운 코드",
    processRequest: "예약을 확인해 주세요.",
    florenceSubtitle: "새해 축제",
    backToHome: "돌아가기",
    visionTitle: "2026 비전 및 미션",
    visionText1: "럭셔리의 미래를 정의하다",
    visionText2: "구찌는 2026년과 그 이후를 향한 완전히 현대적인 패션 접근 방식을 재창조하고 있습니다.",
    expiryDate: "2026년 1월 15일",
  },
  es: {
    loginTitle: "ACCESO EXCLUSIVO 2026",
    loginSubtitle: "Inicie sesión para celebrar el año nuevo con GUCCI.",
    fullName: "Nombre Completo",
    phoneNumber: "Número de Teléfono",
    password: "Código de Acceso",
    startJourney: "INICIAR CELEBRACIÓN",
    menu: "VISIÓN Y MISIÓN",
    validUntil: "Válido Hasta",
    claimReward: "Ver E-Ticket",
    officialWinner: "Ganador Oficial",
    screenshotInstruction: "DESCARGAR E-TICKET DE AÑO NUEVO",
    welcomeTitle: "Celebración de Año Nuevo 2026",
    welcomeText: "Reciba el amanecer de 2026. Gucci y E-Partner le presentan un regalo especial.",
    scratchHere: "Raspe para la Suerte",
    invitation: "Invitación a la Gala",
    specialDiscount: "Golden Scratch 2026",
    giftVoucher: "REGALO DE AÑO NUEVO",
    redeemable: "Canjeable en Boutiques Gucci seleccionadas.",
    congratsTitle: "FELIZ AÑO NUEVO",
    voucherPrefix: "VALE",
    discountPrefix: "DESTELLO",
    claimMessage: "Hola, he ganado un premio de Año Nuevo de Gucci Indonesia",
    codeLabel: "CÓDIGO DE LA SUERTE",
    processRequest: "Por favor, confirme mi reserva.",
    florenceSubtitle: "Celebración de Año Nuevo",
    backToHome: "Volver",
    visionTitle: "Visión y Misión 2026",
    visionText1: "Definiendo el Futuro del Lujo",
    visionText2: "Gucci está reinventando un enfoque totalmente moderno de la moda para el año 2026.",
    expiryDate: "15 de Enero de 2026",
  },
  ar: {
    loginTitle: "تسجيل دخول حصري ٢٠٢٦",
    loginSubtitle: "سجل الدخول للاحتفال بالعام الجديد مع غوتشي.",
    fullName: "الاسم الكامل",
    phoneNumber: "رقم الهاتف",
    password: "رمز الدخول",
    startJourney: "ابدأ الاحتفال",
    menu: "الرؤية والمهمة",
    validUntil: "صالح حتى",
    claimReward: "عرض التذكرة الإلكترونية",
    officialWinner: "الفائز الرسمي",
    screenshotInstruction: "تحميل تذكرة العام الجديد",
    welcomeTitle: "احتفال العام الجديد ٢٠٢٦",
    welcomeText: "استقبل عام ٢٠٢٦. غوتشي و E-Partner يقدمان هدية خاصة لك.",
    scratchHere: "امسح للحصول على الحظ",
    invitation: "دعوة غالا",
    specialDiscount: "جولدن سكراتش ٢٠٢٦",
    giftVoucher: "هدية العام الجديد",
    redeemable: "قابل للاسترداد في متاجر غوتشي المختارة.",
    congratsTitle: "عام جديد سعيد",
    voucherPrefix: "قسيمة",
    discountPrefix: "بريق",
    claimMessage: "مرحباً، لقد فزت بمكافأة العام الجديد من غوتشي إندونيسيا",
    codeLabel: "رمز الحظ",
    processRequest: "يرجى تأكيد حجزي.",
    florenceSubtitle: "احتفال العام الجديد",
    backToHome: "رجوع",
    visionTitle: "الرؤية والمهمة ٢٠٢٦",
    visionText1: "تحديد مستقبل الرفاهية",
    visionText2: "تعيد غوتشي ابتكار نهج حديث كلياً للأزياء لعام ٢٠٢٦ وما بعده.",
    expiryDate: "١٥ يناير ٢٠٢٦",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
